[package]
name = "monod_core"
version = "0.2.0"
edition = "2021"

[lib]
name = "monod_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
num-complex = "0.4"
rustfft = "6"
realfft = "3"
rayon = "1"
numpy = "0.22"
lbfgsb-rs-pure = "0.1.1"
ruanndata = { path = "../../ruanndata", default-features = false, features = ["h5ad"] }

[patch.crates-io]
hdf5-metno-sys = { path = "../../Random/hdf5-metno-sys-patched" }
